version: '3'
services:
  front_end:
    build: ./front_end
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - back_end

  back_end:
    build: ./back_end
    restart: always
    ports:
      - 3000:3000